"""Altering column name in meal table

Revision ID: e931db8dfc3b
Revises: 
Create Date: 2025-04-18 20:48:21.999252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e931db8dfc3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('meal_description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('meal_date_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('meal_on_diet', sa.Boolean(), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('date_time')
        batch_op.drop_column('on_diet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_diet', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('meal_on_diet')
        batch_op.drop_column('meal_date_time')
        batch_op.drop_column('meal_description')
        batch_op.drop_column('meal_name')

    # ### end Alembic commands ###
